# Generated by Django 3.2.4 on 2022-01-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
        ('students', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('scheduling', 'Scheduling'), ('scheduled', 'Scheduled'), ('done', 'Done and Waiting for the Result'), ('canceled', 'Canceled Interview by Company'), ('missed', 'Missed Interview by Student'), ('rejected', 'Rejected'), ('passed', 'Passed'), ('offered', 'Offered'), ('deleted', 'Deleted')], max_length=50, verbose_name='Status')),
                ('interview_type', models.CharField(choices=[('phone_call', 'Phone call'), ('assessment', 'Assessment'), ('video_call', 'Video Call'), ('onsite_interview', 'Onsite Interview')], max_length=50, verbose_name='Type')),
                ('round', models.IntegerField(verbose_name='Round')),
                ('support_tutor', models.CharField(blank=True, max_length=50, null=True, verbose_name='Support Tutor')),
                ('student_scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='Student Scheduled at')),
                ('student_timezone', models.CharField(blank=True, choices=[('usa_eastern', 'USA/Eastern'), ('usa_central', 'USA/Central'), ('usa_mountain', 'USA/Mountain'), ('usa_pacific', 'USA/Pacific'), ('usa_arizona', 'USA/Arizona'), ('usa_alaska', 'USA/Alaska'), ('usa_hawaii', 'USA/Hawaii')], max_length=50, null=True, verbose_name='Student TimeZone')),
                ('ist_scheduled_at', models.DateTimeField(blank=True, null=True, verbose_name='IST Scheduled at')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('recording_url', models.URLField(blank=True, null=True, verbose_name='Recording URL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='applications.application')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'db_table': 'Interview',
            },
        ),
    ]
