# Generated by Django 3.2.4 on 2022-01-25 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone_call', 'Phone call'), ('assessment', 'Assessment'), ('video_call', 'Video Call'), ('onsite_interview', 'Onsite Interview')], max_length=50, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='ist_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='IST Scheduled at'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='round',
            field=models.IntegerField(verbose_name='Round'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='status',
            field=models.CharField(choices=[('scheduling', 'Scheduling'), ('scheduled', 'Scheduled'), ('done', 'Done and Waiting for the Result'), ('canceled', 'Canceled Interview by Company'), ('missed', 'Missed Interview by Student'), ('rejected', 'Rejected'), ('passed', 'Passed'), ('offered', 'Offered'), ('deleted', 'Deleted')], max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='student_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Student Scheduled at'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='support_tutor',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Support Tutor'),
        ),
    ]
