# Generated by Django 3.2.4 on 2022-01-30 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0002_auto_20220125_1110'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='interview',
            table='interview',
        ),
    ]
