# Generated by Django 3.2.4 on 2022-02-03 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interviews', '0004_auto_20220203_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='interview',
            name='submission_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Submission Date'),
        ),
        migrations.AlterField(
            model_name='interview',
            name='interview_type',
            field=models.CharField(choices=[('phone_call', 'Phone call'), ('assessment_real_time', 'Assessment Real Time'), ('assessment_submit', 'Assessment Submit'), ('video_call', 'Video Call'), ('onsite_interview', 'Onsite Interview'), ('take_home_assessment', 'Take Home Assessment')], max_length=50, verbose_name='Type'),
        ),
    ]
