# Generated by Django 3.2.4 on 2022-02-25 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('interviews', '0005_auto_20220203_1310'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(blank=True, db_index=True, max_length=500, verbose_name='Question')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_interview', to='interviews.interview')),
            ],
            options={
                'db_table': 'interview_questions',
            },
        ),
    ]
