# Generated by Django 3.2.4 on 2022-01-30 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '__first__'),
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applied_by', models.CharField(choices=[('tech_is', 'TECH I.S.'), ('student', 'Student')], max_length=50, verbose_name='Applied By')),
                ('status', models.CharField(choices=[('applied', 'Applied'), ('offered', 'Offered'), ('deleted', 'Deleted')], default='applied', max_length=50, verbose_name='Status')),
                ('company_name', models.CharField(max_length=100, verbose_name='Company Name')),
                ('position', models.CharField(max_length=50, verbose_name='Position')),
                ('job_description', models.TextField(blank=True, null=True, verbose_name='Job Description')),
                ('job_post_url', models.URLField(blank=True, null=True, verbose_name='Job Post URL')),
                ('state', models.CharField(choices=[('alabama', 'Alabama'), ('alaska', 'Alaska'), ('arizona', 'Arizona'), ('arkansas', 'Arkansas'), ('california', 'California'), ('colorado', 'Colorado'), ('connecticut', 'Connecticut'), ('delaware', 'Delaware'), ('florida', 'Florida'), ('georgia', 'Georgia'), ('hawaii', 'Hawaii'), ('idaho', 'Idaho'), ('illinoisIndiana', 'IllinoisIndiana'), ('iowa', 'Iowa'), ('kansas', 'Kansas'), ('kentucky', 'Kentucky'), ('louisiana', 'Louisiana'), ('maine', 'Maine'), ('maryland', 'Maryland'), ('massachusetts', 'Massachusetts'), ('michigan', 'Michigan'), ('minnesota', 'Minnesota'), ('mississippi', 'Mississippi'), ('missouri', 'Missouri'), ('montanaNebraska', 'MontanaNebraska'), ('nevada', 'Nevada'), ('new_hampshire', 'New Hampshire'), ('new_jerse', 'New Jerse'), ('new_mexico', 'New Mexico'), ('new_york', 'New York'), ('north_carolina', 'North Carolina'), ('north_dakota', 'North Dakota'), ('ohio', 'Ohio'), ('oklahoma', 'Oklahoma'), ('oregon', 'Oregon'), ('pennsylvaniaRhode_island', 'PennsylvaniaRhode Island'), ('south_carolina', 'South Carolina'), ('south_dakota', 'South Dakota'), ('tennessee', 'Tennessee'), ('texas', 'Texas'), ('utah', 'Utah'), ('vermont', 'Vermont'), ('virginia', 'Virginia'), ('washington', 'Washington'), ('west_virginia', 'West Virginia'), ('wisconsin', 'Wisconsin'), ('wyoming', 'Wyoming')], max_length=50, verbose_name='State')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('job_portal', models.CharField(choices=[('linkedin', 'LinkedIn'), ('indeed', 'Indeed'), ('monster', 'Monster'), ('glassdoor', 'Glassdoor'), ('work_day', 'Work Day'), ('smart_work', 'Smart Work'), ('dice', 'Dice')], max_length=50, verbose_name='Job Portal')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'db_table': 'Application',
            },
        ),
    ]
