# Generated by Django 2.2 on 2022-06-24 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_alter_application_job_portal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='applied_by',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_portal',
        ),
        migrations.RemoveField(
            model_name='application',
            name='job_post_url',
        ),
        migrations.RemoveField(
            model_name='application',
            name='position',
        ),
        migrations.RemoveField(
            model_name='application',
            name='state',
        ),
        migrations.RemoveField(
            model_name='application',
            name='student',
        ),
        migrations.AlterField(
            model_name='application',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
