# Generated by Django 2.2 on 2022-06-22 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comment',
            field=models.TextField(blank=True, db_index=True, null=True, verbose_name='Comment'),
        ),
    ]
