# Generated by Django 3.2.4 on 2022-01-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Name')),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True, verbose_name='Email')),
                ('phone', models.CharField(db_index=True, max_length=50, verbose_name='Phone Number')),
                ('status', models.CharField(choices=[('graduated', 'Graduated'), ('preparing', 'Preaparing'), ('started_application', 'Started Application'), ('pause_application', 'Pause Application'), ('got_offer', 'Got an Offer'), ('failed', 'Failed to Get a Job'), ('deleted', 'Deleted')], db_index=True, max_length=20, verbose_name='Status')),
                ('entrance_ceremony_date', models.DateTimeField(blank=True, null=True, verbose_name='Entrance Ceremony Date')),
                ('graduated_date', models.DateTimeField(blank=True, null=True, verbose_name='Graduated Date')),
                ('application_started_date', models.DateTimeField(blank=True, null=True, verbose_name='Application Started Date')),
                ('got_offer_date', models.DateTimeField(blank=True, null=True, verbose_name='Get Offer Date')),
                ('course', models.CharField(choices=[('web', 'Web Development'), ('data', 'Data Science')], db_index=True, max_length=50, verbose_name='Course')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, max_length=50, verbose_name='Gender')),
                ('certification_url', models.URLField(blank=True, null=True, verbose_name='Certification Url')),
                ('resume_questionnaire_status', models.CharField(choices=[('not_yet', 'Not Yet'), ('done', 'Done')], default='not_yet', max_length=50, verbose_name='Resume Questionnaire Status')),
                ('application_questionnaire_status', models.CharField(choices=[('not_yet', 'Not Yet'), ('done', 'Done')], default='not_yet', max_length=50, verbose_name='Application Questionnaire Status')),
                ('resume_url', models.URLField(blank=True, null=True, verbose_name='Resume Url')),
                ('resume_status', models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support')], default='not_started', max_length=50, verbose_name='Resume Status')),
                ('portfolio_url', models.URLField(blank=True, null=True, verbose_name='Portfolio Url')),
                ('portfolio_status', models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support')], default='not_started', max_length=50, verbose_name='Portfolio Status')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='Github Url')),
                ('github_status', models.CharField(choices=[('not_started', 'Not Started Creating'), ('on_progress', 'On Progress'), ('done', 'Done by Developer Team'), ('reviewed', 'Reviewed by Job Support')], default='not_started', max_length=50, verbose_name='Github Status')),
                ('wakeupserver_status', models.CharField(choices=[('not_yet', 'Not Yet'), ('done', 'Done')], default='not_yet', max_length=50, verbose_name='WakeupServer Status')),
                ('job_support_email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Job Support Email')),
                ('job_support_email_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Job Support Password')),
                ('linkedin_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='LinkedIn Email')),
                ('linkedin_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='LinkedIn Password')),
                ('indeed_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Indeed Email')),
                ('indeed_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Indeed Password')),
                ('monster_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Monster Email')),
                ('monster_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Monster Password')),
                ('glassdoor_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Glassdoor Email')),
                ('glassdoor_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Glassdoor Password')),
                ('dice_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Dice Email')),
                ('dice_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dice Password')),
                ('smart_work_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Smart Work Email')),
                ('smart_work_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Smart Work Password')),
                ('work_day_id', models.EmailField(blank=True, max_length=50, null=True, verbose_name='Work Day Email')),
                ('work_day_password', models.CharField(blank=True, max_length=50, null=True, verbose_name='Work Day Password')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created Datetime')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated Datetime')),
            ],
            options={
                'db_table': 'Student',
            },
        ),
    ]
