# Generated by Django 3.2.4 on 2022-02-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='student_id',
            field=models.CharField(db_index=True, default='', max_length=100, verbose_name='Student ID'),
        ),
    ]
