# Generated by Django 3.2.4 on 2022-02-22 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_auto_20220203_0718'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='prepared_by_dev_team_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Date of Preparation Completed by Developer Team'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('graduated', 'Graduated'), ('preparing', 'Preaparing'), ('perpared_by_dev_team', 'Prepared by Developer Team'), ('started_application', 'Started Application'), ('pause_application', 'Pause Application'), ('got_offer', 'Got an Offer'), ('joined', 'Joined'), ('activated_payment', 'Activated Payment'), ('failed', 'Failed to Get a Job'), ('deleted', 'Deleted')], db_index=True, default='preparing', max_length=20, verbose_name='Status'),
        ),
    ]
